### ISSUE TITLE
"External ID not found in the system: connector-amazon.model_product_template" odoo 10

### ISSUE THREAD

**Issue by EngiSouha** [TristanMozos/connector-amazon#2]
File "/home/dell/PycharmProjects/odoo10/odoo/addons/base/ir/ir_model.py", line 1086, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ParseError: "External ID not found in the system: connector-amazon.model_product_template" while parsing /home/dell/PycharmProjects/odoo10/addons/connector-amazon/wizards/wizard_export_products.xml:59, near
<record id="action_init_wizard_search_products_to_amazon_export" model="ir.actions.server">
        <field name="name">Export to Amazon</field>
        <field name="model_id" ref="connector-amazon.model_product_template"/>
        <field name="state">code</field>
        <field name="condition">True</field>
        <field name="code">action = env.get('amazon.list.products.export.wizard').get_wizard_action()</field>
    </record>

**Comment by TristanMozos** [comment]
Update solve this issue
